### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ddavisgraphics**
Favicons and necessary HTML added, not sure but I think the vagrant box was linking the templates, in production may need looked at.  I'm going to leave this PR open so Mike can see what is coming in.

### CODE REVIEW

**Comment by MichaelRBond** [comment]
Really, all it needed was a proper /favicon.ico 

I touched that file earlier, but it is still 0b. If i remove it i'm still getting a 404 error wit firefox looking for it.

**Comment by ddavisgraphics** [comment]
These are all standard icons for different browsers and mobile devices, if you save a short cut link of the mobile, mac, windows, or pin to safari browsers an icon should show.  I'll look into what other issues your having.

**Comment by MichaelRBond** [comment]
The only issue is that it is missing a /favicon.ico image, in the .ico format, in the root of /public_html. :)

IIRC, it is either a 16x16 pixel icon or 32x32. 

Example: https://github.com/favicon.ico

**Comment by ddavisgraphics** [comment]
This is working now, tested by @trmccormick in vagrant.

**Pull request merged**
